<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="properties">

<!-- Properties file for 4WD MW robot -->
<!-- Created by Stefan -->
<!-- IICT-BAS BG - Version 1.0 from Feb. 15-th, 2021. -->


<!--########### Properties, materials & calibration #####################################################-->

 <!--<xacro:include filename="$(find robot_description)/urdf/gazebo" />-->
  <!-- <xacro:include filename="$(find robot_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find robot_description)/urdf/robco_properties.xacro" />
  <xacro:include filename="$(find robot_description)/urdf/robco_calibration.xacro" /> -->

<!--########### Hardware macros #####################################################-->

  <!-- <xacro:include filename="$(find robot_description)/urdf/macros.xacro" />  
  <xacro:include filename="$(find robot_description)/urdf/robco_macros.xacro" />  
  <xacro:include filename="$(find robot_description)/urdf/robco_2wd_base_macro.xacro" />  
  <xacro:include filename="$(find robot_description)/urdf/robco_body_macro.xacro" />
  <xacro:include filename="$(find robot_description)/urdf/robco_imu_macro.xacro" />
  <xacro:include filename="$(find robot_description)/urdf/robco_rplidar_macro.xacro" />
  <xacro:include filename="$(find robot_description)/urdf/robco_mover4_macro.xacro" />
  <xacro:include filename="$(find robot_description)/urdf/robco_kinect_mount_macro.xacro" />  -->

<!--###################################################################################-->
<!--###################################################################################-->  

  <material name="yellow"><color rgba="0.8 0.8 0.0 1.0" /></material>
  <material name="black"><color rgba="0.15 0.15 0.15 1.0" /></material>
  <material name="dark_grey"><color rgba="0.2 0.2 0.2 1.0" /></material>
  <material name="light_grey"><color rgba="0.4 0.4 0.4 1.0" /></material>

     <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <material name="Blue">
        <color rgba="0.0 0.0 0.8 1.0"/>
    </material>

    <material name="Green">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>

    <material name="Grey">
        <color rgba="0.2 0.2 0.2 1.0"/>
    </material>

    <material name="DarkGrey">
        <color rgba="0.1 0.1 0.1 1.0"/>
    </material>

    <material name="Orange">
        <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
    </material>

    <material name="Brown">
        <color rgba="${222/255} ${207/255} ${195/255} 1.0"/>
    </material>

    <material name="Red">
        <color rgba="0.8 0.0 0.0 1.0"/>
    </material>

    <material name="White">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>


<!--###################################################################################-->
<!--###################################################################################-->  

    <!-- ####### GENERIC CONSTANTS ##### -->

    <!--All units in m-kg-s-radians unit system -->
    <xacro:property name="PI" value="3.1415" />
    <xacro:property name="M_PI" value="3.14159265358979323846264338327950288419716" />
    <!--<xacro:property name="M_PI" value="3.1415926535897931" />-->
    <xacro:property name="M_PI_2" value="1.570796327" />
    <xacro:property name="ROTATE_90_DEGREES" value="1.570796327" />
    <xacro:property name="ROTATE_180_DEGREES" value="ROTATE_90_DEGREES*2" />
    <xacro:property name="DEG_TO_RAD" value="0.017453293" />
    <xacro:property name="SCALE_in_to_m" value="0.0254"/> <!--inches to meters-->
    <xacro:property name="SCALE_mm_to_m" value="0.001"/> <!--milimeters to meters-->
    <xacro:property name="kgcm_to_nm" value="0.0980665" />
    <xacro:property name="gram_to_kg" value="0.001" />


    <!-- ####### ROBOT ORIGINAL CHASSIS CONSTANTS ##### -->

    <!-- ORIGINAL CHASSIS DIMENSIONS  --> 
    <xacro:property name="chassis_lenght" value="${675*SCALE_mm_to_m}" />
    <xacro:property name="chassis_width" value="${530*SCALE_mm_to_m}" />
    <xacro:property name="chassis_height" value="${89*SCALE_mm_to_m}" />
    <xacro:property name="chassis_half_height" value="${chassis_height/2}" />  <!-- 34.5 *SCALE_mm_to_m-->
    <xacro:property name="chassis_weight" value="${19.0-4*0.7}" /> <!-- in kg-->
    <!-- Chassis: distance from the ground to bottom -->
    <xacro:property name="chassis_bottom_z_offset" value="${40.2*SCALE_mm_to_m}" /> 
    <xacro:property name="chassis_center_to_base_footprint_z_offset" value="${40.2*SCALE_mm_to_m + chassis_half_height}" /> 

    
    <!-- EUROPEAN STANDARD 2020 ALUMINIUM EXTRUSION PROFILE DIMENSIONS  --> 
    <xacro:property name="profile_2020_width" value="${20*SCALE_mm_to_m}" />
    <xacro:property name="profile_2020_height" value="${20*SCALE_mm_to_m}" />
    <!-- 2020 1 Meter weights 0.55 kg/m --> <!-- CHECK THE WIGHT FOR THE ACTUAL 2020 PROFILE USED -->
    <xacro:property name="profile_2020_weight_per_mm_lenght" value="${0.55/1000}" /> <!-- in kg/mm-->

    <!-- EUROPEAN STANDARD 2060 ALUMINIUM EXTRUSION PROFILE DIMENSIONS  --> 
    <xacro:property name="profile_2060_width_horizontal" value="${60*SCALE_mm_to_m}" />
    <xacro:property name="profile_2060_height_horizontal" value="${20*SCALE_mm_to_m}" />
    <xacro:property name="profile_2060_height_horizontal" value="${20*SCALE_mm_to_m}" />
    <xacro:property name="profile_2060_height_vertical" value="${60*SCALE_mm_to_m}" />
  <!-- 2060 1 Meter wights 1.21 kg/m --> <!-- CHECK THE WIGHT FOR THE ACTUAL 2060 PROFILE USED -->
    <xacro:property name="profile_2060_weight_per_mm_lenght" value="${1.21/1000}" /> <!-- in kg/mm-->

    <!-- MOTOR WITH SUPPORT AND ELASTIC CLUTCH COUPLER DIMENSIONS  -->
    <!--  2.16 Kg - approximate with a box: h: 69 w: 60 l: 71+133.5+19 =223.5-->
    <xacro:property name="motor_assy_width" value="${60*SCALE_mm_to_m}" />
    <xacro:property name="motor_assy_height" value="${69*SCALE_mm_to_m}" />
    <xacro:property name="motor_assy_lenght" value="${223.5*SCALE_mm_to_m}" />


    <!-- FLANGE / WHEEL HINGE -->
    <!--  0.06 Kg - approximate with cylinder d56.8 h26.4+5=31.4 -->
    <xacro:property name="wheel_flange_diameter" value="${56.8*SCALE_mm_to_m}" />
    <xacro:property name="wheel_flange_lenght" value="${31.4*SCALE_mm_to_m}" />

    <!-- MECANUM WHEEL  SHAFT-->
    <xacro:property name="shaft_diameter" value="${30.0*SCALE_mm_to_m}" />
    <xacro:property name="shaft_radius" value="${shaft_diameter/2}" />
    <!-- <xacro:property name="shaft_lenght" value="${23*SCALE_mm_to_m}" /> -->
    <xacro:property name="shaft_lenght" value="${23.0*SCALE_mm_to_m}" />
    <xacro:property name="shaft_half_lenght" value="${shaft_lenght/2}" />
    <xacro:property name="shaft_mass" value="0.06" /> <!-- in kg-->
    <xacro:property name="shaft_x_offset" value="${307.5*SCALE_mm_to_m}" />
    <xacro:property name="shaft_y_offset" value="${265*SCALE_mm_to_m}" />
    <xacro:property name="shaft_z_offset" value="${34.5*SCALE_mm_to_m}" />

    <!-- MECANUM WHEELS -->
    <xacro:property name="wheel_diameter" value="${6*SCALE_in_to_m}" />
    <xacro:property name="wheel_radius" value="${wheel_diameter/2}" />
    <xacro:property name="wheel_width" value="${46*SCALE_mm_to_m}" />
    <xacro:property name="wheel_weight" value="0.820" /> <!-- in kg-->

    <xacro:property name="left_wheel_x_offset" value="${307.5*SCALE_mm_to_m}" />
    <xacro:property name="left_wheel_y_offset" value="${288.645468*SCALE_mm_to_m}" />
    <xacro:property name="left_wheel_z_offset" value="${34.5*SCALE_mm_to_m}" />


    <!-- <xacro:property name="base_x_origin_to_wheel_origin" value="0.0" /> -->
    <!-- <xacro:property name="base_y_origin_to_wheel_origin" value="0.2" /> VAJNO!!!!!! da se izmeri pak - ot tova zawisi odometriata!!!!!!!!!!! -->
    <!-- <xacro:property name="base_z_origin_to_wheel_origin" value="${-(base_plate_botom_from_base_frame_Z_offset - wheel_radius)}" /> -->

<!-- ####### END ROBOT CONSTANTS ##### -->
<!--###################################################################################-->
<!--###################################################################################-->  



  <!-- BASE PLATE   -->
  <xacro:property name="base_plate_botom_from_base_frame_Z_offset" value="${caster_assy_height}"/>   <!--da go naprawia param za macroto i ne triabva li da e +  round_plate_half_height  -->
  <!-- in kg weight with the battery holder plate bellow -->
  <xacro:property name="base_mass" value="1.75" /> <!-- towa e tegloeoto samo na plochite, da dobavia egloto na akumulatorite dwigateliite i kolelata-->


  <!-- SECOND DECK   -->
  <xacro:property name="top_first_botom_second_deck_distance" value="${0.145}" />
  <xacro:property name="second_deck_from_base_link_Z_offset" value="${top_first_botom_second_deck_distance + round_plate_half_height}"/>
  <xacro:property name="second_deck_height" value="${0.375*SCALE_in_to_m}" />
  <xacro:property name="second_deck_radius" value="${17.75*SCALE_in_to_m/2}" />
  <xacro:property name="second_deck_mass" value="1.5" />   <!-- in kg -->


  <!-- THIRD DECK -->
  <xacro:property name="top_second_botom_third_deck_distance" value="${0.156}" />
  <xacro:property name="third_deck_from_second_deck_Z_offset" value="${top_second_botom_third_deck_distance + round_plate_half_height}"/>
  <xacro:property name="third_deck_height" value="${0.375*SCALE_in_to_m}" />
  <xacro:property name="third_deck_radius" value="${17.75*SCALE_in_to_m/2}" />
  <xacro:property name="third_deck_mass" value="1.5" />   <!-- in kg -->




  
  <!-- CASTER WHEELS -->
  <!-- caster wheel offsets from base origin -->
  <xacro:property name="caster_X_offset_from_base_link" value="0.17"/>

  <!-- caster wheel radius, height and mass -->
  <xacro:property name="caster_assy_height" value="${0.09825}" />
  <xacro:property name="caster_wheel_radius" value="${3*SCALE_in_to_m/2}" />

  <xacro:property name="caster_box_mass" value="0.15" /> <!-- in kg-->
  <xacro:property name="caster_box_height" value="${caster_assy_height- caster_wheel_radius*2}" />
  <xacro:property name="caster_box_width" value="${caster_assy_height - caster_wheel_radius*2}" />
  <xacro:property name="caster_box_lenght" value="${caster_assy_height- caster_wheel_radius*2}" />
  <xacro:property name="caster_sphere_mass" value="0.15" /> <!-- in kg-->
  <xacro:property name="caster_sphere_diameter" value="${caster_wheel_radius*2}" />
  <xacro:property name="caster_sphere_radius" value="${caster_sphere_diameter/2}" />

  <!-- STANDOFFS -->
  <!-- deck standoff offsets -->
  <xacro:property name="standoff_X_offset" value="${0.18 / 2}" />
  <xacro:property name="standoff_Y_offset" value="${0.33 / 2}" />
  
  <!-- MOVER4 ARM -->
  <xacro:property name="mover4_X_offset" value="${round_plate_radius - 0.216}" />
  <xacro:property name="mover4_Y_offset" value="0.0" />
  <xacro:property name="mover4_Z_offset" value="${round_plate_half_height}" />


  <!-- SENSORS -->

  <!-- KINECT -->
  <xacro:property name="kinect_standoff_lenght" value="${0.42775}" /> <!-- ???????measure the real one???????????????-->
  <xacro:property name="kinect_standoff_X_offset" value="${round_plate_radius-0.078}" />
  <xacro:property name="kinect_standoff_Y_offset" value="${0.17 / 2}" />
  <xacro:property name="kinect_standoff_Z_offset" value="${round_plate_height}" />

  <xacro:property name="kinect_mount_point_from_support_plate_X_offset" value="${0.0}"/>
  <xacro:property name="kinect_mount_point_from_support_plate_Y_offset" value="${0.0}" />
  <xacro:property name="kinect_mount_point_from_support_plate_Z_offset" value="${kinect_support_half_height}" />

  <xacro:property name="kinect_support_from_kinect_standoff_0__X_offset" value="${0.0}"/>
  <xacro:property name="kinect_support_from_kinect_standoff_0__Y_offset" value="${-kinect_standoff_Y_offset}"/>
  <xacro:property name="kinect_support_from_kinect_standoff_0__Z_offset" value="${(kinect_standoff_lenght - kinect_support_height)/2+kinect_support_half_height}" />

  <xacro:property name="kinect_support_height" value="${round_plate_height}" />
  <xacro:property name="kinect_support_half_height" value="${kinect_support_height/2}" />
  <xacro:property name="kinect_support_width" value="${kinect_standoff_Y_offset *2 + 0.05}" />
  <xacro:property name="kinect_support_lenght" value="${0.06}" />
  <xacro:property name="kinect_support_mass" value="${.05}" />    <!--in kg-->


    <!-- Define Kinect dimensions using properties -->
   <xacro:property name="kinect_base_x" value="0.072" />
   <xacro:property name="kinect_base_y" value="0.085" />
   <xacro:property name="kinect_base_z" value="0.021" />

   <xacro:property name="kinect_body_x" value="0.07271" />
   <xacro:property name="kinect_body_y" value="0.27794" />
   <xacro:property name="kinect_body_z" value="0.033" />

   <xacro:property name="kinect_base_post_height" value="0.016" />
   <xacro:property name="kinect_base_post_radius" value="0.005" />


  <!-- RPLIDAR A2  -->
  <xacro:property name="rplidar_diameter" value="${0.0757}" />
  <xacro:property name="rplidar_height_of_laser_beam_plane" value="${0.0308}" />
  <xacro:property name="rplidar_height" value="${0.0408}" />
  <xacro:property name="rplidar_X_offset" value="${round_plate_radius-rplidar_diameter/2-0.01}" />
  <xacro:property name="rplidar_Y_offset" value="${0.0}" />
  <xacro:property name="rplidar_Z_offset" value="${round_plate_height+rplidar_height_of_laser_beam_plane}" />
  <xacro:property name="rplidar_mesh_X_offset" value="${0.0}" />
  <xacro:property name="rplidar_mesh_Y_offset" value="${-rplidar_diameter/2 + 0.007}" />
  <xacro:property name="rplidar_mesh_Z_offset" value="${-rplidar_height_of_laser_beam_plane}" />
  

    <!-- CAMERA -->
  <xacro:property name="cameraSize" value="${0.05}"/>
  <xacro:property name="cameraMass" value="${0.1}"/>




<!--###################################################################################-->



</robot>